id: PAF87F511
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA3JT13379
  instance_id: http://purl.bdrc.io/resource/IE3JT13379
  collection_id: http://purl.bdrc.io/resource/PR0ET010
  language_id: None
  title:
    bo:
    - སྤྱོད་འཇུག་གི་ཚིག་འགྲེལ་གཅེས་བཏུས།
  alt_title:
    bo:
    - བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་ཚིག་འགྲེལ་གཅེས་བཏུས།
  author: http://purl.bdrc.io/resource/P2486
  publisher: Various
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    80781198b4364423a499c830111566d5:
      title: སྡིག་དང་སྒྲིབ་པའི་བུད་ཤིང་བསྲེག་ལ་བསྐལ་པའི་མེ་བཞིན་དོ་ཟླ་མེད།་།མི་ཤེས་རྨོངས་པའི་མུན་པ་སེལ་ལ་སྒྲོན་མེའི་འོད་ཀྱིས་མཚོན་དུ་མེད།་།
      volume_number: 1
      base_file: UT3JT13379_001_0001.txt
      reference: http://purl.bdrc.io/resource/VLA5D33F5C2D331975
      image_group: null
      quality: null
  reproductionOf: []
created_at: '2021-12-31T08:21:33.147999'
last_modified_at: '2021-12-31T08:21:33.148006'
statistics:
  total_words: 147279
  total_non_words: 15290
quality:
  non_words_ratio: 0.1
